### PR TITLE
Remove PRE_IOS7 code and resources

### PR DESCRIPTION
**Pull request by charlesroddie**
Fixes build error https://github.com/halkar/xamarin-range-slider/issues/156.
Reduces and simplifies code in the process.
Pre-IOS7 not important to support.

### CODE REVIEW

**Comment by charlesroddie** [comment]
@monkieboy can you test this on your mac please?

**Comment by charlesroddie** [comment]
@halkar is this OK to merge?

**Comment by charlesroddie** [comment]
@halkar

**Comment by halkar** [comment]
Sorry guys. I've seen this PR just didn't have time to review it. Sorry again.

**Comment by halkar** [comment]
Merged. Version 1.0.1 deployed. Thanks a lot @charlesroddie !

**Pull request merged**
