### PR TITLE
#17 #30 added FormatLabel method.

### PR DESCRIPTION
**Pull request by halkar**

### CODE REVIEW

**Comment by willowvil** [comment]
Hi @halkar ,

Is it possible working with dates in the RangeSlider?

Congrats for your work!

Thanks.

**Comment by halkar** [comment]
@willowvil no, but you can encode your dates with integers.
0 -> 1/1/1
736301 -> 05/12/2016
`TimeSpan.FromDays` and `TimeSpan.TotalDays` should help you.

**Comment by willowvil** [comment]
@halkar  I need to show corresponding date while user is mooving the slider. As the only existing event is DragCompleted, I guess I need to use ShowTextAboveThumbs and TextFormat properties. How do I set TextFormat to convert integers into "dd/mm/yyyy"?

Thank you.

**Comment by halkar** [comment]
@willowvil just use new `FormatLabel` method instead. It will fire every time value changed.

**Comment by willowvil** [comment]
@halkar Could you please detail how to set up the slider? I can only see the thumbs, not the bar

sin titulo

Also, I would appreciate if you could show an example of how to use FormatLabel function. I don´t know how to do it.

Thanks!!!

**Comment by halkar** [comment]
@willowvil just set `BarHeight` to 1. Or to 3 ;)

**Comment by willowvil** [comment]
@halkar :) ok is working nice. What about FormatLabel please?

**Comment by halkar** [comment]
Just assign your own handler to `FormatLabel` and return your own formatted label string.

**Comment by willowvil** [comment]
I´m getting an error

sin titulo

**Comment by halkar** [comment]
thanks @willowvil , will investigate. Is that Android, iOS or UWP?

**Comment by willowvil** [comment]
@halkar xamarin.forms, testing Android

**Comment by halkar** [comment]
@willowvil thanks! Please check out v0.6.6.

**Comment by willowvil** [comment]
@halkar yep now doesn´t throw error. But I still don´t know how to use FormatLabel. Can you show an example please?

**Comment by halkar** [comment]
```
        public MyPage()
        {
            InitializeComponent();
            RangeSlider.FormatLabel = FormaLabel;
        }

        private string FormaLabel(Thumb arg1, float arg2)
        {
            return DateTime.Today.AddDays(arg2).ToString();
        }
```

**Comment by willowvil** [comment]
Works fantastic!
It would be great incorporate a separator between both "TextAboveThumbs" when they are together. For example, working with dates when the thumbs are together the result is 01/01/201601/01/2016 instead of 01/01/2016-01/01/2016.

Testing it, I have noticed that the "TextAboveThumbs" disapears when thumbs are on the extremes of the bar, what is not usefull. Don´t you agree?

Thks.

**Comment by halkar** [comment]
Thanks @willowvil, I'll check.
1. Fixing overlapping labels can be a problem, not sure when I will do it.
2. Disappearing labels - I need to investigate.

Are you still testing on Android, Xamarin.Forms?

**Comment by willowvil** [comment]
Yes Android, Xamarin.Forms

sin titulo

**Comment by halkar** [comment]
Thanks @willowvil. Created two bugs #34 and #35.

**Comment by willowvil** [comment]
@halkar  Hi, I can´t set lowervalue and uppervalue. The thumb position is not correct

```
var dateSlider = new RangeSlider()
            {
                HorizontalOptions = LayoutOptions.FillAndExpand,
                BarHeight = 6,
                ShowTextAboveThumbs = true,
                MinimumValue = 0,
                MaximumValue = 10,
                StepValue = 1,
                LowerValue = 0,
                UpperValue = 5
            };
```
sin titulo

**Comment by halkar** [comment]
@willowvil this is a PR, please create an issue.

**Pull request merged**
